---
spring:
  profiles:
      active: prod
---
spring:
    profiles: dev

    jpa:
        # Show or not log for each sql query
        show-sql: true
        hibernate:
             # Hibernate ddl auto (create, create-drop, update)
             ddl-auto: create
             # Naming strategy
             naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

        properties:
             hibernate:
                 # The SQL dialect makes Hibernate generate better SQL for the chosen database
                 dialect: org.hibernate.dialect.MySQL5Dialect

             jadira:
               usertype:
                   # Enable JPA to use Joda Time library
                   autoRegisterUserTypes: true
                   # Enable the currency for the JPA to create the table
                   currencyCode: ZAR

server:
    port: 9099

keystore:
    file: src/main/resources/infoware.p12
    password: infoware
    type: PKCS12
    alias: tomcat

eureka:
   password: infoware
   instance:
       preferIpAddress: true
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://user:${eureka.password}@127.0.0.1:8761/eureka/
     registryFetchIntervalSeconds: 5

tomcat:
  jdbc:
    pool:
      url: jdbc:mysql://127.0.0.1:3306/rhys_limited
      username: root
      password: infoware
      initial-size: 5
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
      driver-class-name: com.mysql.jdbc.Driver
      max_size: 50
      min_size: 5

---
spring:
    profiles: QA

    jpa:
        # Show or not log for each sql query
        show-sql: true
        hibernate:
             # Hibernate ddl auto (create, create-drop, update)
             ddl-auto: update
             # Naming strategy
             naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

        properties:
             hibernate:
                 # The SQL dialect makes Hibernate generate better SQL for the chosen database
                 dialect: org.hibernate.dialect.MySQL5Dialect

             jadira:
               usertype:
                   # Enable JPA to use Joda Time library
                   autoRegisterUserTypes: true
                   # Enable the currency for the JPA to create the table
                   currencyCode: ZAR

server:
    port: 9099

keystore:
    file: infoware.p12
    password: infoware
    type: PKCS12
    alias: tomcat

eureka:
   password: infoware
   instance:
       preferIpAddress: true
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://user:${eureka.password}@discovery-service:8761/eureka/
     registryFetchIntervalSeconds: 5

tomcat:
  jdbc:
    pool:
      url: jdbc:mysql://52.30.160.174:3306/users
      username: root
      password: infoware
      initial-size: 5
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
      driver-class-name: com.mysql.jdbc.Driver
      max_size: 50
      min_size: 5
---
spring:
    profiles: prod

    jpa:
        # Show or not log for each sql query
        show-sql: true
        hibernate:
             # Hibernate ddl auto (create, create-drop, update)
             ddl-auto: none
             # Naming strategy
             naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

        properties:
             hibernate:
                 # The SQL dialect makes Hibernate generate better SQL for the chosen database
                 dialect: org.hibernate.dialect.MySQL5Dialect

             jadira:
               usertype:
                   # Enable JPA to use Joda Time library
                   autoRegisterUserTypes: true
                   # Enable the currency for the JPA to create the table
                   currencyCode: ZAR

server:
    port: 9099

keystore:
    file: D:\\rhys-certificate-activity\\server.p12
    #file: /root/project_rhys/project_rhys_phase2/auth-service/server.p12
    password: changeit
    type: PKCS12
    #alias: tomcat

eureka:
   password: infoware
   instance:
       preferIpAddress: true
   client:
#     registerWithEureka: true
#     fetchRegistry: true
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
     registryFetchIntervalSeconds: 5

hystrix:
  threadpool:
    default:
      # Maximum number of concurrent requests when using thread pools (Default: 10)
      coreSize: 100
      # Maximum LinkedBlockingQueue size - -1 for using SynchronousQueue (Default: -1)
      maxQueueSize: -1
      # Queue size rejection threshold (Default: 5)
      queueSizeRejectionThreshold: 5
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 100
      execution:
        isolation:
#          strategy: SEMAPHORE, no thread pool but timeout handling stops to work
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 120000

tomcat:
  jdbc:
    pool:
      url: jdbc:mysql://185.173.226.118:3306/rhys_limited
      username: root
      password: 6bBNqpVqDe3FP79Y
      initial-size: 5
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
      driver-class-name: com.mysql.jdbc.Driver
      max_size: 50
      min_size: 5

---
